### ISSUE TITLE
Why has this app disappeared from the Google Play Store?

### ISSUE THREAD

**Issue by Starcr0ss** [tanallnight/SimpleWeather-IssueTracker#3]

**Comment by tanallnight** [comment]
I shut down the app about 4 years ago cause it was unsustainable with the API costs.

**Comment by Starcr0ss** [comment]
Ok, understood. I saw the app on a list of material design weather apps and
it had piqued my interest. It's a shame that it couldn't stay, but I
completely understand and respect the decision.
